export const API_END_POINT = {
    LOGIN : "/auth/login",
    REGISTER_ACCOUNT: "/auth/register",
    VERIFY_EMAIL: "/auth/verify-email",
    RESEND_OTP: "/auth/resend-otp",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    USERS: "/users",
    BOARDS: "/boards",
    POSTS: "/posts",
    VOTES: "/votes",
    COMMENTS: "/comments",
    REPORTS: "/reports",
    S3_UPLOAD: "/s3/upload",
    S3_UPLOAD_BULK: "/s3/upload/bulk",
    S3_FILES: "/s3/files",
    EYE_MASKED_IMAGES: "/eye-masked-images",
    EYE_MASKED_IMAGES_BULK: "/eye-masked-images/bulk",
    
}